"""Initial (blank) database

Revision ID: 1e3c5824cdad
Revises: None
Create Date: 2015-05-14 07:49:27.471881

"""

# revision identifiers, used by Alembic.
revision = '1e3c5824cdad'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
