"""* Initial version of database

Revision ID: 5ad37140062b
Revises: 1e3c5824cdad
Create Date: 2015-05-14 07:50:59.928384

"""

# revision identifiers, used by Alembic.
revision = '5ad37140062b'
down_revision = '1e3c5824cdad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=30), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_name', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_name')
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solutions',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'problem_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solutions')
    op.drop_table('problem')
    op.drop_table('member')
    op.drop_table('difficulty')
    ### end Alembic commands ###
